[package]
name = "cursor-code-rust"
version = "1.0.0"
edition = "2021"
description = "Rust demonstration for build system analysis"
authors = ["Cursor Code Team <team@cursor-code.com>"]
license = "MIT"
repository = "https://github.com/cursor/cursor-code-rust"
homepage = "https://cursor-code.com"
documentation = "https://docs.rs/cursor-code-rust"
readme = "README.md"
keywords = ["haxe", "reflection", "ast", "analysis", "rust"]
categories = ["development-tools", "parsing"]
exclude = [
    "tests/fixtures/*",
    "benches/*",
    ".github/*",
]

[dependencies]
serde = { version = "1.0.180", features = ["derive"] }
serde_json = "1.0.104"
tokio = { version = "1.29.1", features = ["full"] }
clap = { version = "4.3.19", features = ["derive"] }
anyhow = "1.0.72"
thiserror = "1.0.44"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
regex = "1.9.3"

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }
proptest = "1.2.0"
tempfile = "3.7.0"
pretty_assertions = "1.4.0"
insta = "1.31.0"

[features]
default = ["reflection", "analysis"]
reflection = []
analysis = ["reflection"]
experimental = []

[lib]
name = "cursor_code"
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "cursor-code"
path = "src/bin/main.rs"

[[bench]]
name = "ast_analysis"
harness = false

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = true

[profile.dev]
debug = true
opt-level = 0

[profile.test]
debug = true

[workspace]
members = [
    "cursor-code-core",
    "cursor-code-cli",
    "cursor-code-web",
]

[workspace.dependencies]
cursor-code-core = { path = "cursor-code-core" }
serde = { version = "1.0.180", features = ["derive"] }
tokio = { version = "1.29.1", features = ["full"] }